### ISSUE TITLE
SBN-ND TPC readout issue

### ISSUE THREAD

**Issue by wesketchum** [SBNSoftware/sbndaq-artdaq#13]
From @wbadgett 

> FYI, there's a new issue at SBN-ND with TPC readout:  events are not being taken, even tho' triggers are being sent.  A bit different from the D0 XMIT issue.   It happens in EXT, CTRL and CALIB modes.

**Comment by wbadgett** [comment]
When running in EXT mode, i verified with a 'scope that triggers are being sent from the PTB, also the LEDs are flashing indicating the Nevis trigger module is receiving triggers.

**Comment by wesketchum** [comment]
OK, I think @wbadgett reports this as fixed due to a missing fcl file. I'm closing it, but can reopen if needed.

**Comment by wbadgett** [comment]
The FCL issue was separate, the original issue is still present

Pby will not have time to zoom this afternoon, maybe tomorrow

________________________________
